global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
  - job_name: 'gpu'
    static_configs:
      - targets: ['dcgm-exporter:9400']
